spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER:guest}
    password: ${RABBITMQ_DEFAULT_PASS:guest}

management:
  endpoints:
    web:
      exposure:
        # expose only these actuator endpoints
        include: health,info,metrics
  endpoint:
    health:
      show-details: always   # return component details (DB, disk, etc.)
